import "../../styles/globals.css";
import styled from "styled-components";
import Header from "../Components/Header";
import LeftBar from "../Components/LeftBar";
import Head from "next/head";

import "bootstrap/dist/css/bootstrap.css";

import { AuthContext, AuthProvider } from "../providers/context";
import { useState, useEffect, useContext } from "react";

export const Container = styled.div`
  /* background-color: rgb(230, 230, 230); */
  background-color: #1f262f;
  /* background-color: rgb(26, 33, 42); */

  display: grid;
  grid-template-areas:
    "header header"
    "leftbar main";

  /* overflow: hidden; */

  grid-column-gap: 1px;
  grid-row-gap: 1px;
  grid-gap: 1px;

  grid-template-columns: 300px 1fr;
  grid-template-rows: 90px 1fr;
`;

// export const LoadingScreen = styled.div`
//   width: 300px;
//   height: 300px;
//   background-color: red;
//   color: white;
//   background-color: black;
//   /* background: linear-gradient(20deg, blue, blueviolet); */
//   z-index: 5;
//   border-radius: 10px;

//   position: relative;
//   display: flex;
//   justify-content: center;
//   align-items: center;
//   align-self: center;
//   font-size: 25px;
//   /* display: "none"; */
//   display: ${(props) => props.visibility};
// `;

export const Load = styled.div`
  /* position: absolute; */
  /* display: block; */
  display: flex;
  position: absolute;
  width: calc(100vw - 300px);
  height: calc(100vh - 90px);
  margin-top: 90px;
  margin-left: 300px;
  z-index: 20000000;
  background-color: rgba(0, 0, 0, 0.8);

  display: flex;
  justify-content: center;
  align-items: center;
  color: white;

  /* font-size: 50px; */
  /* font-size: 100px; */
  font-family: monospace;
  flex-wrap: wrap;
  word-wrap: break-word;
  overflow: hidden;

  display: ${(props) => props.visibility};
`;

function MyApp({ Component, pageProps }) {
  const [vis, setVis] = useState("none");
  const [messageLoading, setMessageLoading] = useState("");
  // const [visible, setVisible] = useState("none");

  const changeVis = (v, message) => {
    setVis(v);
    setMessageLoading(message);
    console.log(v);
  };

  return (
    <AuthProvider>
      <Head>
        <title>Cards NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />

        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital@0;1&display=swap"
          rel="stylesheet"
        />

        {/* <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossOrigin="anonymous"
        /> */}
        {/* bootstrap */}

        {/* <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital@0;1&display=swap"
          rel="stylesheet"
        /> */}
      </Head>

      <Container>
        <Load visibility={vis}>
          <h1>{messageLoading}</h1>
        </Load>
        <Header />
        <LeftBar />
        <Component changeVis={changeVis} {...pageProps} />
      </Container>
    </AuthProvider>
  );
}

export default MyApp;
